version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-next-app
    ports:
      - "3000:3000"
    volumes:
      - .:/my-app
      - /my-app/node_modules
